### ISSUE TITLE
Filter node: Unable to get filtered points

### ISSUE THREAD

**Issue by rumaisaabdulhai** [hasauino/rrt_exploration#19]
Hello,

I hope you are doing well. I am trying to use your rrt_exploration package in my research with my quadcopter (in Gazebo). I am using ROS Kinetic with an Ubuntu 16.04 Linux machine. I think I have set everything up correctly. You can see my two launch files [here](https://github.com/rumaisaabdulhai/quad_sim/blob/master/quadcopter_exploration/launch/quadcopter_exploration.launch) and [here](https://github.com/rumaisaabdulhai/quad_sim/blob/master/quadcopter_exploration/launch/includes/move_baseSafe.launch).

When I run the exploration launch file, all the nodes are initialized as you can see [here](https://drive.google.com/file/d/1A4bLAUw_UXtD_ZjCiMEl0HL5edm15hiZ/view?usp=sharing). After I publish the 5 points in the order you specified, I am able to see the detected points published to the /detected_points topic as you can see [here](https://drive.google.com/file/d/1ihSygS5b-JF9UP3YH1C8uyIKIEJ_qLqU/view?usp=sharing). However, there are no filtered points being published to the /filtered_points topic as you can see [here](https://drive.google.com/file/d/1Z-ZyFp62zEb7SmSUZS6i9Y0XWmSh3fVX/view?usp=sharing). I realized that the filter node was killed for some reason and that is why I could not get any filtered points ([here](https://drive.google.com/file/d/1QHgIhYEvzB5GTSywLNpKVKF-l5vcWcCW/view?usp=sharing) is the rosnode list after I published the 5 points). As you mentioned in your explanation of the package, the filtered points are sent to the assigner which sends a 2D navigation goal to the robot. I'm not sure why the filter node was killed. If you have any suggestions on how I could fix this issue I would greatly appreciate it. Thank you so much for your time!

**Comment by hasauino** [comment]
Hello,
The move_base node doesn't work with your robot.. am I right? (it's for mobile robot only, and I saw in your package that the quadrotor has a action server already which controls it).
I ran your package (first ran `quadcopter_gazebo/launch/quadcopter.launch`, then `quadcopter_exploration/launch/quadcopter_exploration.launch`). Everything was working just fine, except the assigner was not moving the quadrotor since the assigner only supports `move_base_node` (unfortunately)...
If you want to modify the assigner, so it support your robot, you only need to modify this file:
[rrt_exploration/scripts/functions.py](https://github.com/hasauino/rrt_exploration/blob/master/scripts/functions.py#L64)

**Comment by rumaisaabdulhai** [comment]
I have used the move base node before and it has worked ([here](https://youtu.be/cq0wKcm7asA) is a video of it working). If you comment out the rrt_exploration nodes in the `quadcopter_exploration.launch` file and just run the `quadcopter.launch` file, the `quadcopter_takeoff_land.launch` file, and the exploration launch file, and set a 2D navigation goal the quadcopter should move towards the goal point.

**Comment by hasauino** [comment]
oh, I didn't know there are packages which use the move_base for quadcopters as well.
I check it again, the only problem was the assigner not moving the robot, every time a goal to an unknown region is sent, the planner rejected it..
 since all the goals here lie in the unknown region, there is [one parameter](https://github.com/rumaisaabdulhai/quad_sim/blob/master/quadcopter_navigation/config/navfn_global_planner_params.yaml#L4) in `navfn_global_planner_params.yaml` that needs to be changed:

```
allow_unknown: true 
```
After that, everything was working just fine

**Comment by rumaisaabdulhai** [comment]
Hi, I just ran the code with your suggestion and it works! It's just a bit slow, but I hope I can fix it by modifying the params. Thanks for your help!
