### ISSUE TITLE
Some doubts about the paper and code

### ISSUE THREAD

**Issue by FFuChen** [hasauino/rrt_exploration#30]
Excuse me for a moment. I don't seem to see how the obstacle avoidance logic between robots is implemented in your paper. Can you briefly explain it

**Comment by FFuChen** [comment]
I mean the avoidance process between robots during exploration

**Comment by hasauino** [comment]
Hi @FFuChen 
I have not implemented that. But it is already taken care of to some extent by the navigation stack (the global planner).
Even though the navigation stack is meant for static obstacles, it was performing quite well. The cost map used by the global planner has a fast update rate from the laser scanner than the map used for exploration.

Additionally, the task allocator will ideally scatter robots away from one another during the whole mission. 

Because of these reasons, I haven't encountered a problem during my experiments, but it might occur in certain scenarios

**Comment by FFuChen** [comment]
Thank you very much!

**Comment by hasauino** [comment]
You are welcome
